#!/usr/bin/perl -w

=head1 NAME

dh_dpatch_unpatch - unapply patches listed in debian/patched

=cut

use strict;
use Debian::Debhelper::Dh_Lib;

=head1 SYNOPSIS

B<dh_dpatch_unpatch> [S<I<debhelper options>>]

=head1 DESCRIPTION

dh_dpatch_unpatch simply calls B<dpatch deapply-all>.
All patches listed in B<debian/patched> are then unapplied in the
current directory. The command does not fail if the patches have
already been unapplied.

=head1 EXAMPLES

dh_dpatch_unpatch is usually called indirectly in a rules file via the
dh command.

	%:
		dh --with dpatch $@

It can also be direcly called in the clean rule.

	clean:
		dh_testdir
		dh_testroot
		[ ! -f Makefile ] || $(MAKE) clean
		dh_dpatch_unpatch
		dh_clean

=cut

init();

complex_doit('dpatch deapply-all || test $? = 2');

=head1 SEE ALSO

L<debhelper(7)>, L<dh(1)>.

This program is meant to be used together with debhelper.

=head1 AUTHOR

Hideki Yamane <henrich@debian.or.jp>, stolen from dh_quilt_unpatch written by Raphael Hertzog <hertzog@debian.org>

=cut

